name: Main

on: [push,pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 8.0.x

    - uses: actions/checkout@v2

    - name: Build and test
      run: |
        ./restore.sh
        ./build.sh
        ./test.sh

