name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - uses: actions/checkout@v2

    - name: Build and test
      run: |
        ./restore.sh
        ./build.sh
        ./test.sh

    - name: Publish
      run: |
        dotnet pack --configuration Release ./figtree/figtree.fsproj
        dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}

