name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 8.0.x

    - uses: actions/checkout@v2

    - name: Restore
      run: |
        dotnet tool restore
        dotnet paket restore

    - name: Build
      run: |
        dotnet build /WarnAsError

    - name: Test
      run: |
        dotnet test

    - name: Fable
      run: |
        dotnet tool run fable figtree

    - name: Publish
      run: |
        dotnet pack --configuration Release ./figtree/figtree.fsproj
        dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}

